[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "learn-to-rank-mslr"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = ["src"]